#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-redis
Version  : 5.3.2
Release  : 15
URL      : https://pecl.php.net/get/redis-5.3.2.tgz
Source0  : https://pecl.php.net/get/redis-5.3.2.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause PHP-3.01
Requires: php-redis-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
DESCRIPTION
LZF is an extremely fast (not that much slower than a pure memcpy)
compression algorithm. It is ideal for applications where you want to
save *some* space but not at the cost of speed. It is ideal for
repetitive data as well. The module is self-contained and very small.

%package lib
Summary: lib components for the php-redis package.
Group: Libraries

%description lib
lib components for the php-redis package.


%prep
%setup -q -n redis-5.3.2
cd %{_builddir}/redis-5.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20190902/redis.so
