#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: phpize
# autospec version: v3
# autospec commit: c1050fe
#
Name     : php-redis
Version  : 6.0.2
Release  : 83
URL      : https://pecl.php.net/get/redis-6.0.2.tgz
Source0  : https://pecl.php.net/get/redis-6.0.2.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause PHP-3.01
Requires: php-redis-lib = %{version}-%{release}
Requires: php-redis-license = %{version}-%{release}
BuildRequires : buildreq-php
BuildRequires : perl(Getopt::Long)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
DESCRIPTION
LZF is an extremely fast (not that much slower than a pure memcpy)
compression algorithm. It is ideal for applications where you want to
save *some* space but not at the cost of speed. It is ideal for
repetitive data as well. The module is self-contained and very small.

%package lib
Summary: lib components for the php-redis package.
Group: Libraries
Requires: php-redis-license = %{version}-%{release}

%description lib
lib components for the php-redis package.


%package license
Summary: license components for the php-redis package.
Group: Default

%description license
license components for the php-redis package.


%prep
%setup -q -n redis-6.0.2
cd %{_builddir}/redis-6.0.2
pushd ..
cp -a redis-6.0.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
mkdir -p %{buildroot}/usr/share/package-licenses/php-redis
cp %{_builddir}/redis-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/php-redis/e2815bf94c6ff64afbc20d3403dc45ea5c73c6f0 || :
cp %{_builddir}/redis-%{version}/liblzf/LICENSE %{buildroot}/usr/share/package-licenses/php-redis/9a0e277bb547589f33bbd1fc939e6057703a95ae || :
%make_install

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20230831/redis.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/php-redis/9a0e277bb547589f33bbd1fc939e6057703a95ae
/usr/share/package-licenses/php-redis/e2815bf94c6ff64afbc20d3403dc45ea5c73c6f0
